// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0JEf1Th43H0FSG3VChpzD9kTH8fkwoAo',
    appId: '1:315373856404:web:721722b995971064a6f681',
    messagingSenderId: '315373856404',
    projectId: 'medical-management-17fc6',
    authDomain: 'medical-management-17fc6.firebaseapp.com',
    storageBucket: 'medical-management-17fc6.firebasestorage.app',
    measurementId: 'G-TGGRFMQSX5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS1dZxMZbvT8YlefebfPJfKsbsHqPu9Zs',
    appId: '1:315373856404:android:e5b1d0fb0b8d1ce5a6f681',
    messagingSenderId: '315373856404',
    projectId: 'medical-management-17fc6',
    storageBucket: 'medical-management-17fc6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0JEf1Th43H0FSG3VChpzD9kTH8fkwoAo',
    appId: '1:315373856404:ios:PLACEHOLDER',
    messagingSenderId: '315373856404',
    projectId: 'medical-management-17fc6',
    storageBucket: 'medical-management-17fc6.firebasestorage.app',
    iosBundleId: 'medical-management-app.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0JEf1Th43H0FSG3VChpzD9kTH8fkwoAo',
    appId: '1:315373856404:ios:PLACEHOLDER',
    messagingSenderId: '315373856404',
    projectId: 'medical-management-17fc6',
    storageBucket: 'medical-management-17fc6.firebasestorage.app',
    iosBundleId: 'medical-management-app.com',
  );
}
